//! Bundled presets. `presets/default-config.toml` is generated by
//! `tools/gen_presets.py` and embedded here; it is written to disk on first run.

use crate::Config;

pub const DEFAULT_CONFIG_TOML: &str = include_str!("../../../presets/default-config.toml");

/// The first-run configuration. Panics only if the bundled file is invalid,
/// which the test below guards against.
pub fn default_config() -> Config {
    Config::from_toml(DEFAULT_CONFIG_TOML).expect("bundled default-config.toml is valid")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::action::Action;
    use crate::keys::ParsedChord;

    #[test]
    fn bundled_default_config_is_valid() {
        let cfg = default_config();
        assert_eq!(
            cfg.transport_table().unwrap().len(),
            7,
            "CW, CCW, press, 4 swipes"
        );
        assert!(cfg.profiles.len() >= 9, "expected the MVP profile set");
        assert_eq!(cfg.default_profile.bindings.len(), 7);
        assert!(cfg.resolver().uses_titles(), "YouTube profile needs titles");

        // Every chord in every profile must parse, or it would fail at runtime.
        let all = std::iter::once(&cfg.default_profile).chain(cfg.profiles.iter());
        for p in all {
            assert!(!p.name.is_empty());
            for (ev, b) in &p.bindings {
                if let Action::Keys { chord } = &b.action {
                    chord
                        .0
                        .parse::<ParsedChord>()
                        .unwrap_or_else(|e| panic!("{}/{ev}: {e}", p.name));
                }
            }
        }
        // App profiles must be matchable on at least one platform.
        for p in &cfg.profiles {
            assert!(
                !p.app_match.windows_exe.is_empty() || !p.app_match.macos_bundle.is_empty(),
                "{} has no match rule",
                p.name
            );
        }
    }
}
