//! Bundled presets. `presets/default-config.toml` is generated by
//! `tools/gen_presets.py` and embedded here; it is written to disk on first run.

use crate::Config;

/// The Windows first-run configuration (F17-F24 inputs, Windows chords).
pub const DEFAULT_CONFIG_TOML_WINDOWS: &str = include_str!("../../../presets/default-config.toml");
/// The macOS first-run configuration (F13-F20 inputs, Cmd chords).
pub const DEFAULT_CONFIG_TOML_MACOS: &str =
    include_str!("../../../presets/default-config.macos.toml");

/// The first-run configuration for the platform this build runs on.
#[cfg(target_os = "macos")]
pub const DEFAULT_CONFIG_TOML: &str = DEFAULT_CONFIG_TOML_MACOS;
#[cfg(not(target_os = "macos"))]
pub const DEFAULT_CONFIG_TOML: &str = DEFAULT_CONFIG_TOML_WINDOWS;

/// The first-run configuration. Panics only if the bundled file is invalid,
/// which the test below guards against.
pub fn default_config() -> Config {
    Config::from_toml(DEFAULT_CONFIG_TOML).expect("bundled default-config.toml is valid")
}

/// The per-application catalog (`presets/apps.json`), embedded so the UI can
/// serve it and so the test below can validate every chord in it.
pub const APPS_CATALOG_JSON: &str = include_str!("../../../presets/apps.json");

#[cfg(test)]
mod tests {
    use super::*;
    use crate::action::Action;
    use crate::keys::ParsedChord;

    /// Every chord in the generated app catalog must parse with the engine's
    /// parser, or it would fail the moment a user picked it.
    #[test]
    fn both_default_configs_parse_and_fit_their_platform() {
        let win = Config::from_toml(DEFAULT_CONFIG_TOML_WINDOWS).expect("windows default config");
        let mac = Config::from_toml(DEFAULT_CONFIG_TOML_MACOS).expect("macos default config");
        assert_eq!(win.transport.len(), mac.transport.len());
        // Every macOS input is a key macOS can deliver.
        for (ev, e) in &mac.transport {
            assert!(
                e.code.key.macos_keycode().is_some(),
                "{ev} uses {:?}",
                e.code.key
            );
        }
        // Every chord in the macOS profiles parses.
        for p in &mac.profiles {
            for (ev, b) in &p.bindings {
                if let crate::action::Action::Keys { chord, .. } = &b.action {
                    chord
                        .0
                        .parse::<crate::keys::ParsedChord>()
                        .unwrap_or_else(|e| panic!("{} / {ev}: {e}", p.name));
                }
            }
        }
    }

    #[test]
    fn apps_catalog_chords_parse() {
        let v: serde_json::Value = serde_json::from_str(APPS_CATALOG_JSON).unwrap();
        let apps = v["apps"].as_array().expect("apps array");
        assert!(apps.len() >= 12);
        let mut checked = 0usize;
        let mut check_action = |a: &serde_json::Value, where_: String| {
            let action: Action = serde_json::from_value(a.clone())
                .unwrap_or_else(|e| panic!("{where_}: not an Action: {e}"));
            let chords: Vec<&str> = match &action {
                Action::Keys { chord, .. } => vec![chord.0.as_str()],
                Action::Sequence { chords } => chords.iter().map(|c| c.0.as_str()).collect(),
                _ => vec![],
            };
            for c in chords {
                c.parse::<ParsedChord>()
                    .unwrap_or_else(|e| panic!("{where_}: chord `{c}`: {e}"));
                checked += 1;
            }
        };
        for app in apps {
            let id = app["id"].as_str().unwrap_or("?");
            for act in app["actions"].as_array().unwrap_or(&vec![]) {
                for plat in ["windows", "mac", "linux"] {
                    if let Some(a) = act.get(plat) {
                        if !a.is_null() {
                            check_action(a, format!("{id}/{}/{plat}", act["name"]));
                        }
                    }
                }
            }
            if let Some(defaults) = app["defaults"].as_object() {
                for (ev, b) in defaults {
                    ev.parse::<crate::event::SemanticEvent>()
                        .unwrap_or_else(|e| panic!("{id}/defaults/{ev}: {e}"));
                    check_action(&b["action"], format!("{id}/defaults/{ev}"));
                }
            }
        }
        assert!(
            checked > 1000,
            "expected thousands of chords, checked {checked}"
        );
    }

    #[test]
    fn bundled_default_config_is_valid() {
        let cfg = default_config();
        assert_eq!(
            cfg.transport_table().unwrap().len(),
            7,
            "CW, CCW, press, 4 swipes"
        );
        assert!(cfg.profiles.len() >= 9, "expected the MVP profile set");
        assert_eq!(cfg.default_profile.bindings.len(), 7);
        assert!(cfg.resolver().uses_titles(), "YouTube profile needs titles");

        // Every chord in every profile must parse, or it would fail at runtime.
        let all = std::iter::once(&cfg.default_profile).chain(cfg.profiles.iter());
        for p in all {
            assert!(!p.name.is_empty());
            for (ev, b) in &p.bindings {
                if let Action::Keys { chord, .. } = &b.action {
                    chord
                        .0
                        .parse::<ParsedChord>()
                        .unwrap_or_else(|e| panic!("{}/{ev}: {e}", p.name));
                }
            }
        }
        // App profiles must be matchable on at least one platform.
        for p in &cfg.profiles {
            assert!(
                !p.app_match.windows_exe.is_empty() || !p.app_match.macos_bundle.is_empty(),
                "{} has no match rule",
                p.name
            );
        }
    }
}
